### ISSUE TITLE
Thanks for this.

### ISSUE THREAD

**Issue by GravityAssisted** [helgee/Dopri.jl#1]
I am planning to use this in my adventures in Julia. Thanks for making this wrapper. Let me know if there are any known issues at this point.

Nitin

**Comment by helgee** [comment]
Hey! You are welcome.

The supplied build script does not work to well and the performance was (last time I checked) not as good as expected. Apart from that, I am not aware of any showstoppers. Bug reports and PRs are always welcome!

**Comment by helgee** [comment]
@GravityAssisted FYI: The package is now in the official repository and in the process of making it publication-ready I have fixed a lot of issues. So you might want to switch to the new version!

**Comment by GravityAssisted** [comment]
Okay.. great..
