### ISSUE TITLE
current state vector in solout 

### ISSUE THREAD

**Issue by loicspace** [helgee/Dopri.jl#5]
Hi,

First, thanks for that package! 
I'm 
I may be missing something but I'm having a problem with the current state vector variable when using the optional solout. Specifically, assuming the notation: 

solout!(told, t, y, contd, params) = ... return dopricode[:nominal]

Then, y returns a float and typeof(y) called within the function returns Float64 while my state has dimension 6. Experimenting a little, it looks like y contains the last component of the current state vector. Like I said, I'm probably just missing something. I attached a simple example with a lower order ODE system that replicates my issue in case that helps. 

Thank you,
Loic

[testingDOPRI.txt](https://github.com/helgee/Dopri.jl/files/251295/testingDOPRI.txt)

**Comment by helgee** [comment]
Good catch. I did not load the array correctly.
